services:
  db:
    image: postgres:16
    container_name: egov-postgres
    environment:
      POSTGRES_DB: egov
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - egov_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d egov"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: .              # <-- backend folder (current)
      dockerfile: Dockerfile  # backend/Dockerfile
    container_name: egov-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/egov
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "true"
      SERVER_PORT: "8080"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../frontend     # <-- от backend/ към frontend/
      dockerfile: Dockerfile   # frontend/Dockerfile
    container_name: egov-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"              # app at http://localhost:5173

volumes:
  egov_pgdata:
